name: Logger
 
on: [push]
 
jobs:
  build:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        dotnet: [ '3.0.100', '3.0.101'] 
        os: ['ubuntu-latest']
    
    name: Build for .NET ${{ matrix.dotnet }}

steps:  
    - uses: actions/checkout@v1
     
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ matrix.dotnet }}
       
    - name: Build with dotnet
      run: dotnet build Solution.sln --configuration Release
     
    - name: Run Tests - Serilog
      run: dotnet test Core.Logger.Serilog.Tests/Core.Logger.Serilog.Tests.csproj --configuration Release --no-build
