name: Logger
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet: [ '3.0.100','3.0.101', '3.1.100' ]

    name: Build for .NET Core ${{ matrix.dotnet }}
        steps:  
        - name: List SDK Availables
          run: dotnet --list-sdks
          
        - name: Setup checkout@v1
          uses: actions/checkout@v1
          with:
            dotnet-version: ${{ matrix.dotnet }}
     
        - name: Setup setup-dotnet@v1
          uses: actions/setup-dotnet@v1
          with:
            dotnet-version: ${{ matrix.dotnet }}
       
        - name: Build with dotnet
          run: dotnet build Solution.sln --configuration Release
     
        - name: Run Tests - Serilog
          run: dotnet test Kitpymes.Core.Logger.Serilog.Tests/Kitpymes.Core.Logger.Serilog.Tests.csproj --configuration Release --no-build